name: accessibility_app
description: An accessibility-focused app with voice commands, smart reminders, and health features.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  speech_to_text: ^6.6.0
  text_to_speech: ^0.1.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  audioplayers: ^5.2.1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/ 