// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwAFhaBNTF44GsPXJf2o7uKP2Ps9ZI_Is',
    appId: '1:717455876904:web:4ed4e828bca141acab661d',
    messagingSenderId: '717455876904',
    projectId: 'thriveminds-953a9',
    authDomain: 'thriveminds-953a9.firebaseapp.com',
    storageBucket: 'thriveminds-953a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwAFhaBNTF44GsPXJf2o7uKP2Ps9ZI_Is',
    appId: '1:717455876904:android:4ed4e828bca141acab661d',
    messagingSenderId: '717455876904',
    projectId: 'thriveminds-953a9',
    authDomain: 'thriveminds-953a9.firebaseapp.com',
    storageBucket: 'thriveminds-953a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwAFhaBNTF44GsPXJf2o7uKP2Ps9ZI_Is',
    appId: '1:717455876904:ios:4ed4e828bca141acab661d',
    messagingSenderId: '717455876904',
    projectId: 'thriveminds-953a9',
    authDomain: 'thriveminds-953a9.firebaseapp.com',
    storageBucket: 'thriveminds-953a9.firebasestorage.app',
    iosBundleId: 'com.example.thriveMind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwAFhaBNTF44GsPXJf2o7uKP2Ps9ZI_Is',
    appId: '1:717455876904:macos:4ed4e828bca141acab661d',
    messagingSenderId: '717455876904',
    projectId: 'thriveminds-953a9',
    authDomain: 'thriveminds-953a9.firebaseapp.com',
    storageBucket: 'thriveminds-953a9.firebasestorage.app',
    iosBundleId: 'com.example.thriveMind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwAFhaBNTF44GsPXJf2o7uKP2Ps9ZI_Is',
    appId: '1:717455876904:windows:4ed4e828bca141acab661d',
    messagingSenderId: '717455876904',
    projectId: 'thriveminds-953a9',
    authDomain: 'thriveminds-953a9.firebaseapp.com',
    storageBucket: 'thriveminds-953a9.firebasestorage.app',
  );
}
